update templates

diff --git a/codebundles/azure-rw-acr-helm-update/.test/Taskfile.yaml b/codebundles/azure-rw-acr-helm-update/.test/Taskfile.yaml
--- a/codebundles/azure-rw-acr-helm-update/.test/Taskfile.yaml
+++ b/codebundles/azure-rw-acr-helm-update/.test/Taskfile.yaml
@@ -46,7 +46,7 @@ tasks:
         popd > /dev/null
 
         # Check if any of the required cluster variables are empty
-        if [ -z "$cluster1_name" ] || [ -z "$cluster1_server" ] || [ -z "$cluster1_resource_group" ]; then
+        if [ -z "$cluster_name" ] || [ -z "$cluster_server" ] || [ -z "$cluster_resource_group" ]; then
           echo "Error: Missing cluster details. Ensure Terraform plan has been applied."
           exit 1
         fi
@@ -77,6 +77,9 @@ tasks:
           codeBundles: ["$codebundle"]
         custom: 
           kubernetes_distribution_binary: kubectl
+          private_registry: azure_acr
+          azure_acr_registry: runwhensandboxacr.azurecr.io
+          azure_service_principal_secret_name: azure-sp
         EOF
     silent: true
 
@@ -84,7 +87,6 @@ tasks:
     desc: "Run RunWhen Local Discovery on test infrastructure"
     cmds:
       - |
-        BUILD_DIR=/workspace/runwhen-local/src
         CONTAINER_NAME="RunWhenLocal"
         if docker ps -q --filter "name=$CONTAINER_NAME" | grep -q .; then
           echo "Stopping and removing existing container $CONTAINER_NAME..."
@@ -95,17 +97,14 @@ tasks:
         else
           echo "No existing container named $CONTAINER_NAME found."
         fi
-        
-        echo "Cleaning up output directory..."
-        rm -rf output || { echo "Failed to remove output directory"; exit 1; }
-        mkdir output && chmod 777 output || { echo "Failed to set permissions"; exit 1; }
 
-        ## Building Container Image
-        docker build -t runwhen-local:test -f $BUILD_DIR/Dockerfile $BUILD_DIR
+        echo "Cleaning up output directory..."
+        sudo rm -rf output || { echo "Failed to remove output directory"; exit 1; }
+        mkdir output && chmod 777 output || { echo "Failed to set permissions"; exit 1; }
 
         echo "Starting new container $CONTAINER_NAME..."
 
-        docker run --name $CONTAINER_NAME -p 8081:8081 -v "$(pwd)":/shared -d runwhen-local:test || {
+        docker run --name $CONTAINER_NAME -p 8081:8081 -v "$(pwd)":/shared -d ghcr.io/runwhen-contrib/runwhen-local:0.8.2 || {
           echo "Failed to start container"; exit 1;
         }
 
